eureka:
    client:
        fetch-registry: false
        register-with-eureka: false
    server:
        enableSelfPreservation: true
logging:
    level:
        org:
            springframework:
                web:
                    servlet:
                        DispatcherServlet: DEBUG
server:
    port: 8761
spring:
    zipkin:
        base-url: http://localhost:9411/