eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
logging:
    level:
        org:
            hibernate:
                SQL: DEBUG
            springframework:
                web:
                    servlet:
                        DispatcherServlet: DEBUG
server:
    port: 8081
spring:
    application:
        name: Inscritos
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: springpoc
        url: jdbc:mysql://${MYSQL_HOST:arbex.adm.br}:3306/arbexa09_springpoc?useSSL=false
        username: arbexa09_springpoc
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
 a: teste
 b: teste2
 c: teste3
